### ISSUE TITLE
Deploy Blog to Heroku

### ISSUE THREAD

**Issue by bernardo5** [bernardo5/Blog#6]
## Why

It is an easy way to make the blog public and easily deployed.

## Tasks

* [ ] Create heroku account and project

* [ ] Adapt structure to deploy the code

* [ ] Link the project to the master branch for automatic deployments

* [ ] Perform the deployment

### Start Criteria

* [ ] Have an Heroku account created

### Finish Criteria

* [ ] Have the website live and connected to Github master branch
